### ISSUE TITLE
Configure L2SI Attenuator

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-tmo-motion#11]
Once it exists, of course

**Comment by klauer** [comment]
AT1K4, the attenuator noted in this issue belongs in kfe-motion (https://github.com/pcdshub/lcls-plc-kfe-motion/issues/56)

**Comment by klauer** [comment]
Related to the above, I'm hoping to aggregate PLC information into one spot: https://github.com/pcdshub/plc-summary/blob/master/docs/source/axes.rst

Of course this is too late for past work as with AT1K4, but we look forward to preventing such issues in the future. There may be more information or something better to show in these - not sure yet - and not sure where to classify it, issue-wise.
